// libs/react-utils/src/lib/utils/portalPage.tsx
import type { CSSProperties, ReactNode } from 'react'
import { useEffect, useMemo, useState } from 'react'
import { useAppState, useUserService } from '@onecx/react-integration-interface'
import { useTranslation } from 'react-i18next'

/**
 * Props for PortalPage wrapper.
 *
 * @param children - Page content to render.
 * @param permission - Permission or list of permissions required for access.
 * @param helpArticleId - Help article identifier for help integration.
 * @param pageName - Display name for the page.
 * @param applicationId - Application identifier for analytics/telemetry.
 * @param className - Optional CSS class name for the wrapper.
 * @param style - Optional inline styles for the wrapper.
 */
export interface PortalPageProps {
  children: ReactNode
  permission?: string | string[]
  helpArticleId?: string
  pageName?: string
  applicationId?: string
  className?: string
  style?: CSSProperties
}

const DEFAULT_CONTAINER_STYLE: CSSProperties = {
  display: 'block',
  padding: 'var(--page-padding, 1rem)',
  height: '100%',
}

/**
 * React PortalPage implementation mirroring the Angular portal-page component.
 *
 * @param children - Page content to render.
 * @param permission - Permission or list of permissions required for access.
 * @param helpArticleId - Help article identifier for help integration.
 * @param pageName - Display name for the page.
 * @param applicationId - Application identifier for analytics/telemetry.
 * @param className - Optional CSS class name for the wrapper.
 * @param style - Optional inline styles for the wrapper.
 * @returns Portal page wrapper element.
 */
export const PortalPage = ({
  children,
  permission,
  helpArticleId,
  pageName,
  applicationId,
  className,
  style,
}: PortalPageProps) => {
  const { currentPage$ } = useAppState()
  const { hasPermission } = useUserService()
  const { t } = useTranslation()
  const [hasAccess, setHasAccess] = useState(!permission)

  useEffect(() => {
    let isMounted = true

    const checkPermission = async () => {
      if (!permission) {
        setHasAccess(true)
        return
      }
      try {
        const result = await hasPermission(permission)
        if (isMounted) {
          setHasAccess(result)
        }
      } catch (error) {
        console.warn('Failed to resolve permission for PortalPage', error)
        if (isMounted) {
          setHasAccess(false)
        }
      }
    }

    checkPermission()

    return () => {
      isMounted = false
    }
  }, [hasPermission, permission])

  useEffect(() => {
    if (!helpArticleId && typeof location !== 'undefined') {
      console.warn(
        `Portal Page on url ${location.pathname} does not have 'helpArticleId' set. Set to some unique string in order to support help management feature.`
      )
    }

    const path = typeof document !== 'undefined' ? document.location.pathname : ''

    const permissionValue = Array.isArray(permission) ? permission.join(',') : (permission ?? '')

    currentPage$.publish({
      path,
      helpArticleId: helpArticleId ?? '',
      permission: permissionValue,
      pageName: pageName ?? '',
      applicationId: applicationId ?? '',
    })
  }, [applicationId, currentPage$, helpArticleId, pageName, permission])

  const containerStyle = useMemo(() => ({ ...DEFAULT_CONTAINER_STYLE, ...style }), [style])
  const containerClassName = ['portal-page', className].filter(Boolean).join(' ')
  const unauthorizedTitle = t('OCX_PORTAL_PAGE.UNAUTHORIZED_TITLE')
  const unauthorizedMessage = t('OCX_PORTAL_PAGE.UNAUTHORIZED_MESSAGE')
  const missingPermissionMessage = t('OCX_PORTAL_PAGE.MISSING_PERMISSION', { permission })

  return (
    <div className={containerClassName} style={containerStyle}>
      <div className="content-wrapper">
        {hasAccess ? (
          children
        ) : (
          <>
            <h3>{unauthorizedTitle}</h3>
            <p>
              {unauthorizedMessage} <span>{missingPermissionMessage}</span>
            </p>
          </>
        )}
      </div>
    </div>
  )
}

// libs/angular-utils/src/lib/components/portal-page/portal-page.component.ts
import { Component, Input, OnInit, computed, inject, input } from '@angular/core'
import { AppStateService } from '@onecx/angular-integration-interface'
import { Observable, of, switchMap, tap } from 'rxjs'
import { CommonModule } from '@angular/common'
import { TranslateModule } from '@ngx-translate/core'
import { PermissionService } from '../../services/permission.service'
import { toObservable } from '@angular/core/rxjs-interop'

@Component({
  selector: 'ocx-portal-page',
  templateUrl: './portal-page.component.html',
  styleUrls: ['./portal-page.component.scss'],
  standalone: true,
  imports: [CommonModule, TranslateModule],
})
export class PortalPageComponent implements OnInit {
  private appState = inject(AppStateService)
  private permissionService = inject(PermissionService)
  private trueObservable = of(true)

  permission = input<string>('')
  helpArticleId = input<string>('')
  pageName = input<string>('')
  applicationId = input<string>('')

  hasAccess$ = toObservable(this.permission).pipe(
    tap((permission) => console.log('Checking access for permission:', permission)),
    switchMap((permission) => (permission ? this.permissionService.hasPermission(permission) : this.trueObservable)),
    tap((hasAccess) => console.log('Access result:', hasAccess))
  )

  ngOnInit(): void {
    if (!this.helpArticleId()) {
      console.warn(
        `ocx-portal-page on url ${location.pathname} does not have 'helpArticleId' set. Set to some unique string in order to support help management feature.`
      )
    }

    this.appState.currentPage$.publish({
      path: document.location.pathname,
      helpArticleId: this.helpArticleId(),
      permission: this.permission(),
      pageName: this.pageName(),
      applicationId: this.applicationId(),
    })
  }
}

<div class="content-wrapper">
  @if (hasAccess$ | async) {
  <ng-content></ng-content>
  } @else {
  <h3>{{'OCX_PORTAL_PAGE.UNAUTHORIZED_TITLE' | translate}}</h3>
  <p>
    {{'OCX_PORTAL_PAGE.UNAUTHORIZED_MESSAGE' | translate}}
    <span>{{'OCX_PORTAL_PAGE.MISSING_PERMISSION' | translate : {permission: permission} }}</span>
  </p>
  }
</div>
