// libs/react-remote-components/src/lib/components/slotComponent.tsx
import {
  useEffect,
  useState,
  useRef,
  useCallback,
  FC,
  ReactElement,
  ReactNode,
  ComponentRef,
  ComponentType,
} from 'react'

import { BehaviorSubject, combineLatest, Observable } from 'rxjs'
import { RemoteComponentInfo, SlotComponentConfiguration, useSlot } from '../contexts/slotContext'
import { RemoteComponentConfig } from '../model/remote-component-config.model'

type SlotProps = {
  name: string
  inputs?: Record<string, unknown>
  outputs?: Record<string, (payload: any) => void>
  skeleton?: ReactNode
}

type CreateComponentProps = {
  componentType: ComponentType<any | undefined>
  componentInfo: SlotComponentConfiguration
  permissions: string[]
  viewContainer: HTMLDivElement | null
  index: number
}

type ViewContainersRef = HTMLDivElement

const viewContainers$ = new BehaviorSubject<ViewContainersRef[]>([])

const _assignedComponents$ = new BehaviorSubject<(ComponentRef<any> | HTMLElement)[]>([])

export const SlotComponent: FC<SlotProps> = ({ name, inputs = {}, outputs = {}, skeleton }) => {
  const slotService = useSlot()
  const [components, setComponents] = useState<any[]>([])

  let components$: Observable<SlotComponentConfiguration[]>

  const inputs$ = useRef(new BehaviorSubject(inputs))
  const outputs$ = useRef(new BehaviorSubject(outputs))

  const setComponentsObservable = () => {
    components$ = slotService.getComponentsForSlot(name)
  }

  const setViewContainerRef = (element: HTMLDivElement | null) => {
    if (element) {
      viewContainers$.next([...viewContainers$.value, element])
    }
  }

  useEffect(() => {
    if (!slotService) {
      console.error(`SLOT_SERVICE token was not provided. ${name} slot will not be filled with data.`)
      return
    }
    setComponentsObservable()

    const assignedCompsSub = combineLatest([_assignedComponents$, inputs$.current, outputs$.current]).subscribe(
      ([components, inputs, outputs]) => {
        components.forEach((component) => {
          updateComponentData(component as HTMLElement, inputs, outputs)
        })
      }
    )

    const subscription = combineLatest([viewContainers$, components$]).subscribe(([viewContainers, components]) => {
      if (viewContainers && viewContainers.length === components.length) {
        components.forEach((componentInfo, index) => {
          if (componentInfo.componentType) {
            Promise.all([
              Promise.resolve(componentInfo.componentType),
              Promise.resolve(componentInfo.permissions),
            ]).then(([componentType, permissions]) => {
              const component = createComponent({
                componentType: componentType as ComponentType<any>,
                componentInfo,
                permissions,
                viewContainer: viewContainers[index],
                index,
              })

              if (component) {
                _assignedComponents$.next([..._assignedComponents$.getValue(), component])
              }
            })
          }
        })
      }
    })

    return () => {
      subscription.unsubscribe()
      assignedCompsSub.unsubscribe()
    }
  }, [])

  const createComponent = ({
    componentType,
    componentInfo,
    viewContainer,
    permissions,
  }: CreateComponentProps): ReactElement | HTMLElement | null => {
    if (!viewContainer) return null

    const rcConfig = {
      appId: componentInfo.remoteComponent.appId,
      productName: componentInfo.remoteComponent.productName,
      baseUrl: componentInfo.remoteComponent.baseUrl,
      permissions: permissions,
    } satisfies RemoteComponentConfig

    if (componentType) {
      const element = document.createElement(componentInfo.remoteComponent.elementName || '')
      ;(element as any)['ocxRemoteComponentConfig'] = rcConfig

      addDataStyleId(element, componentInfo.remoteComponent)
      addDataStyleIsolation(element)

      viewContainer.appendChild(element)

      return element
    }

    return null
  }

  const addDataStyleId = (element: HTMLElement, rcInfo: RemoteComponentInfo) => {
    element.dataset['styleId'] = `${rcInfo.productName}|${rcInfo.appId}`
  }

  const addDataStyleIsolation = (element: HTMLElement) => {
    element.dataset['styleIsolation'] = ''
  }

  const updateComponentData = useCallback(
    (component: ReactElement | HTMLElement, inputs: Record<string, unknown>, outputs: Record<string, any>) => {
      setProps(component, inputs)
      setProps(component, outputs)
    },
    []
  )

  const setProps = (component: ReactElement | HTMLElement, props: Record<string, unknown>) => {
    if (!component) return

    Object.entries(props).forEach(([name, value]) => {
      if (component instanceof HTMLElement) {
        ;(component as any)[name] = value
      } else {
        component.props = {
          ...(component.props as object),
          [name]: value,
        }
      }
    })
  }

  useEffect(() => {
    const subscription = components$?.subscribe({
      next: (newComponents) => {
        setComponents(newComponents)
      },
      error: (err) => console.error('Error in slot components observable:', err),
    })

    return () => subscription?.unsubscribe()

    // @ts-expect-error Is used before
  }, [components$])

  return (
    <div>
      {components.map((_component, index) => {
        return (
          <div key={'slot component: ' + index} id="slot" ref={(el) => setViewContainerRef(el)}>
            {skeleton && skeleton}
          </div>
        )
      })}
    </div>
  )
}

export default SlotComponent

// libs/angular-remote-components/src/lib/components/slot/slot.component.ts
import {
  Component,
  ComponentRef,
  ContentChild,
  EventEmitter,
  Input,
  OnDestroy,
  OnInit,
  QueryList,
  TemplateRef,
  Type,
  ViewChildren,
  ViewContainerRef,
  inject,
} from '@angular/core'
import { Technologies } from '@onecx/integration-interface'
import { BehaviorSubject, Observable, Subscription, combineLatest } from 'rxjs'
import { ocxRemoteComponent } from '../../model/remote-component'
import { RemoteComponentConfig } from '../../model/remote-component-config.model'
import { RemoteComponentInfo, SLOT_SERVICE, SlotComponentConfiguration, SlotService } from '../../services/slot.service'

@Component({
  standalone: false,
  selector: 'ocx-slot[name]',
  templateUrl: './slot.component.html',
})
export class SlotComponent implements OnInit, OnDestroy {
  private slotService = inject<SlotService>(SLOT_SERVICE, { optional: true })

  @Input()
  name!: string

  private _assignedComponents$ = new BehaviorSubject<(ComponentRef<any> | HTMLElement)[]>([])

  /**
   * Inputs to be passed to components inside a slot.
   *
   * @example
   *
   * ## Slot usage
   * ```
   * <ocx-slot name="my-slot-name" [inputs]="{ header: myHeaderValue }">
   * </ocx-slot>
   * ```
   *
   * ## Remote component definition
   * ```
   * export class MyRemoteComponent: {
   * ⁣@Input() header: string = ''
   * }
   * ```
   *
   * ## Remote component template
   * ```
   * <p>myInput = {{header}}</p>
   * ```
   */
  private _inputs$ = new BehaviorSubject<Record<string, unknown>>({})
  @Input()
  get inputs(): Record<string, unknown> {
    return this._inputs$.getValue()
  }
  set inputs(value: Record<string, unknown>) {
    this._inputs$.next({
      ...this._inputs$.getValue(),
      ...value,
    })
  }

  /**
   * Outputs to be passed to components inside a slot as EventEmitters. It is important that the output property is annotated with ⁣@Input().
   *
   * @example
   *
   * ## Component with slot in a template
   * ```
   * ⁣@Component({
standalone: false,   *  selector: 'my-component',
   *  templateUrl: './my-component.component.html',
   * })
   * export class MyComponent {
   *  buttonClickedEmitter = new EventEmitter<string>()
   *  constructor() {
   *    this.buttonClickedEmitter.subscribe((msg) => {
   *      console.log(msg)
   *    })
   *  }
   * }
   * ```
   *
   * ## Slot usage in my-component.component.html
   * ```
   * <ocx-slot name="my-slot-name" [outputs]="{ buttonClicked: buttonClickedEmitter }">
   * </ocx-slot>
   * ```
   *
   * ## Remote component definition
   * ```
   * export class MyRemoteComponent: {
   *  ⁣@Input() buttonClicked = EventEmitter<string>()
   *  onButtonClick() {
   *    buttonClicked.emit('payload')
   *  }
   * }
   * ```
   *
   * ## Remote component template
   * ```
   * <button (click)="onButtonClick()">Emit message</button>
   * ```
   */
  private _outputs$ = new BehaviorSubject<Record<string, EventEmitter<any>>>({})
  @Input()
  get outputs(): Record<string, EventEmitter<any>> {
    return this._outputs$.getValue()
  }
  set outputs(value: Record<string, EventEmitter<any>>) {
    this._outputs$.next({
      ...this._outputs$.getValue(),
      ...value,
    })
  }

  _viewContainers$ = new BehaviorSubject<QueryList<ViewContainerRef> | undefined>(undefined)
  @ViewChildren('slot', { read: ViewContainerRef })
  set viewContainers(value: QueryList<ViewContainerRef>) {
    this._viewContainers$.next(value)
  }

  @ContentChild('skeleton') skeleton: TemplateRef<any> | undefined

  subscription: Subscription | undefined
  components$: Observable<SlotComponentConfiguration[]> | undefined

  ngOnInit(): void {
    if (!this.slotService) {
      console.error(`SLOT_SERVICE token was not provided. ${this.name} slot will not be filled with data.`)
      return
    }
    this.components$ = this.slotService.getComponentsForSlot(this.name)
    combineLatest([this._assignedComponents$, this._inputs$, this._outputs$]).subscribe(
      ([components, inputs, outputs]) => {
        components.forEach((component) => {
          this.updateComponentData(component, inputs, outputs)
        })
      }
    )
    this.subscription = combineLatest([this._viewContainers$, this.components$]).subscribe(
      ([viewContainers, components]) => {
        if (viewContainers && viewContainers.length === components.length) {
          components.forEach((componentInfo, i) => {
            if (componentInfo.componentType) {
              Promise.all([
                Promise.resolve(componentInfo.componentType),
                Promise.resolve(componentInfo.permissions),
              ]).then(([componentType, permissions]) => {
                const component = this.createComponent(componentType, componentInfo, permissions, viewContainers, i)
                if (component) this._assignedComponents$.next([...this._assignedComponents$.getValue(), component])
              })
            }
          })
        }
      }
    )
  }

  private createComponent(
    componentType: Type<unknown> | undefined,
    componentInfo: { remoteComponent: RemoteComponentInfo },
    permissions: string[],
    viewContainers: QueryList<ViewContainerRef>,
    i: number
  ): ComponentRef<any> | HTMLElement | undefined {
    const viewContainer = viewContainers.get(i)
    viewContainer?.clear()
    viewContainer?.element.nativeElement.replaceChildren()
    if (componentType) {
      const componentRef = viewContainer?.createComponent<any>(componentType)
      const componentHTML = componentRef?.location.nativeElement as HTMLElement
      this.addDataStyleId(componentHTML, componentInfo.remoteComponent)
      if (componentRef && 'ocxInitRemoteComponent' in componentRef.instance) {
        ;(componentRef.instance as ocxRemoteComponent).ocxInitRemoteComponent({
          appId: componentInfo.remoteComponent.appId,
          productName: componentInfo.remoteComponent.productName,
          baseUrl: componentInfo.remoteComponent.baseUrl,
          permissions: permissions,
        })
      }
      componentRef?.changeDetectorRef.detectChanges()
      return componentRef
    } else if (
      componentInfo.remoteComponent.technology === Technologies.WebComponentModule ||
      componentInfo.remoteComponent.technology === Technologies.WebComponentScript
    ) {
      if (componentInfo.remoteComponent.elementName) {
        const element = document.createElement(componentInfo.remoteComponent.elementName)
        this.addDataStyleId(element, componentInfo.remoteComponent)
        ;(element as any)['ocxRemoteComponentConfig'] = {
          appId: componentInfo.remoteComponent.appId,
          productName: componentInfo.remoteComponent.productName,
          baseUrl: componentInfo.remoteComponent.baseUrl,
          permissions: permissions,
        } satisfies RemoteComponentConfig
        viewContainer?.element.nativeElement.appendChild(element)
        return element
      }
    }

    return
  }

  private addDataStyleId(element: HTMLElement, rcInfo: RemoteComponentInfo) {
    element.dataset['styleId'] = `${rcInfo.productName}|${rcInfo.appId}`
  }

  private updateComponentData(
    component: ComponentRef<any> | HTMLElement | undefined,
    inputs: Record<string, unknown>,
    outputs: Record<string, EventEmitter<unknown>>
  ) {
    this.setProps(component, inputs)
    this.setProps(component, outputs)
  }

  private setProps(component: ComponentRef<any> | HTMLElement | undefined, props: Record<string, unknown>) {
    if (!component) return

    Object.entries(props).map(([name, value]) => {
      if (component instanceof HTMLElement) {
        ;(component as any)[name] = value
      } else {
        component.setInput(name, value)
      }
    })
  }

  ngOnDestroy(): void {
    this.subscription?.unsubscribe()
  }
}

@for (component of (components$ | async); track component) {
<div #slot data-style-isolation>
  @if (skeleton) {
  <ng-container [ngTemplateOutlet]="skeleton"></ng-container>
  }
</div>
}
